version: "3.9"  # Specifies the version of docker-compose
services:
  # Application services
  users:
    build: ./server/users  # Path to the Dockerfile for users
    ports:
      - "8001:80"  # Maps port 80 of the container to 8001 on the host
  posts:
    build: ./server/posts  # Path to the Dockerfile for posts
    ports:
      - "8002:9001"  # Maps port 9001 of the container to 8002 on the host
  notifications:
    build: ./server/notifications  # Path to the Dockerfile for notifications
    ports:
      - "8003:9000"  # Maps port 9000 of the container to 8003 on the host
  relationships:
    build: ./server/relationships  # Path to the Dockerfile for relationships
    ports:
      - "8004:80"  # Maps port 80 of the container to 8004 on the host
  search:
    build: ./server/search  # Path to the Dockerfile for search
    ports:
      - "8005:3000"  # Maps port 3000 of the container to 8005 on the host